<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Tunner.Observability.FunctionalTests</AssemblyName>
    <RootNamespace>Tunner.Observability.FunctionalTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Tunner.Observability/Tunner.Observability.csproj" />
  </ItemGroup>
</Project>
