<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Tunner.Governance.FunctionalTests</AssemblyName>
    <RootNamespace>Tunner.Governance.FunctionalTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Tunner.Governance/Tunner.Governance.csproj" />
  </ItemGroup>
</Project>