<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>tunner</AssemblyName>
    <RootNamespace>Tunner.Governance</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="JsonSchema.Net" />
  </ItemGroup>
</Project>